# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js.03-04.cl CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-22.04
    # runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        mkdir -p $HOME/.local/bin && cp -nv ttfautohint.bin $HOME/.local/bin/ttfautohint
        chmod -v 755 $HOME/.local/bin/ttfautohint
        # cp -an build.d .build
        # cp -fv config.1.json config.json
    - run: |
        python -m venv afdko_env
        source afdko_env/bin/activate
        # python -m pip install --upgrade pip
        # python -m pip install https://github.com/adobe-type-tools/afdko/releases/download/3.9.6/afdko-3.9.6-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
        # python -m pip install https://github.com/adobe-type-tools/afdko/releases/download/4.0.2/afdko-4.0.2-py3-none-manylinux_2_28_x86_64.whl
        python -m pip install afdko
        npm install
    - run: |
        source afdko_env/bin/activate
        cp -fv CL/config.03.ncl.json config.json && npm run build -- ttf
        # npm run build -- full-clean
    - run: |
        source afdko_env/bin/activate
        cp -fv CL/config.04.scl.json config.json && npm run build -- ttf
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: out_03-04_cl
        path: out
        if-no-files-found: warn
